---
- name: "Wait for uptime-kuma to start"
  ansible.builtin.wait_for:
    port: "{{ kuma_port }}"
    timeout: 30

- name: "Set up uptime-kuma credentials"
  lucasheld.uptime_kuma.setup:
    api_url: http://127.0.0.1:{{ kuma_port }}
    api_username: "{{ kuma_api_username }}"
    api_password: "{{ kuma_api_password }}"

- name: "Login with credentials once and register the result"
  register: result
  lucasheld.uptime_kuma.login:
    api_url: http://127.0.0.1:{{ kuma_port }}
    api_username: "{{ kuma_api_username }}"
    api_password: "{{ kuma_api_password }}"

- name: "Extract the token from the result and set it as fact"
  ansible.builtin.set_fact:
    kuma_api_token: "{{ result.token }}"

- name: "Create monitors"
  loop: "{{ kuma_monitors }}"
  lucasheld.uptime_kuma.monitor:
    api_url: http://127.0.0.1:{{ kuma_port }}
    api_token: "{{ kuma_api_token }}"
    type: "{{ item.type }}"
    name: "{{ item.name }}"
    state: present
    interval: "{{ item.interval | default(60) }}"
    description: "{{ item.description | default(omit) }}"
    url: "{{ item.url | default(omit) }}"

- name: "Add Telegram notifications"
  when:
    - kuma_tg_bot_token is defined
    - kuma_tg_chat_id is defined
  lucasheld.uptime_kuma.notification:
    api_url: http://127.0.0.1:{{ kuma_port }}
    api_token: "{{ kuma_api_token }}"
    type: telegram
    name: Telegram alerts
    isDefault: true
    applyExisting: true
    telegramBotToken: "{{ kuma_tg_bot_token }}"
    telegramChatID: "{{ kuma_tg_chat_id }}"
    state: present
