# kics-scan disable=2e8d4922-8362-4606-8c14-aa10466a1ce3
---
- name: Verify
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  vars:
    test_admin_username: admin
    # kics-scan ignore-line
    test_admin_password: SDjj3$k4g9dhsjd__1dj

  pre_tasks:
    - name: "Include default vars"
      ansible.builtin.include_vars:
        dir: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/defaults/'
        extensions:
          - 'yml'

  tasks:
    - name: "Verify uptime-kuma responds to HTTP requests"
      register: this
      until: this is ansible.builtin.success
      retries: 3
      delay: 3
      ansible.builtin.uri:
        url: "http://127.0.0.1:{{ kuma_port }}"
        method: GET
        status_code: 200

    - name: "Get monitor information"
      register: monitors
      lucasheld.uptime_kuma.monitor_info:
        api_url: http://127.0.0.1:3001
        api_username: "{{ test_admin_username }}"
        api_password: "{{ test_admin_password }}"

    - name: "Check that the expected monitor exists"
      ansible.builtin.assert:
        that: "monitors.monitors | selectattr('name', 'equalto', 'push-test') | list | length > 0"
        success_msg: "The expected push monitor is configured correcly"
        fail_msg: "The expected push monitor is missing or incorrectly configured"

    - name: "Check that the expected monitor push interval is correctly set"
      ansible.builtin.assert:
        that: "monitors.monitors | selectattr('interval', 'equalto', 30) | list | length > 0"
        success_msg: "The expected push monitor is configured correcly"
        fail_msg: "The expected push monitor is missing or incorrectly configured"

    - name: "Check that the expected monitor description is correctly set"
      ansible.builtin.assert:
        that: "monitors.monitors | selectattr('description', 'equalto', 'Test push monitor') | list | length > 0"
        success_msg: "The expected push monitor is configured correcly"
        fail_msg: "The expected push monitor is missing or incorrectly configured"
